//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute("45bceaf8-01ba-48c5-8d26-68c67ffe5b1a")]
[assembly: System.Reflection.AssemblyCompanyAttribute("api")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+ecdd9b449b655e2a1e6532d249cceb90461f81d2")]
[assembly: System.Reflection.AssemblyProductAttribute("api")]
[assembly: System.Reflection.AssemblyTitleAttribute("api")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Généré par la classe MSBuild WriteCodeFragment.

